import { cp, mkdir, mkdtemp, rename, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

import { assertSerializedHarnessTargetExport, canonicalHarnessJson } from '../HarnessMount/remoteTargetContract.js'
import type { HarnessTargetJsonSchema } from '../HarnessMount/targetExport.js'
import { convertToCamelCase } from '../helper/string/convertToCamelCase.impl.js'
import { convertToKebabCase } from '../helper/string/convertToKebabCase.impl.js'
import { convertToPascalCase } from '../helper/string/convertToPascalCase.impl.js'
import type { FullServiceDefinition } from '../helper/types/FullServiceDefinition.js'

/** @internal Generate client and contract text together from the stored root exports. */
export function generateHarnessClientArtifacts(definitions: FullServiceDefinition, clientName = 'EventBridgeClient') {
	const files = new Map<string, string>()
	const imports: string[] = []
	const namespaces: Record<'agent' | 'workflow', Map<string, Map<string, string[]>>> = {
		agent: new Map(),
		workflow: new Map(),
	}
	for (const [serviceName, versions] of Object.entries(definitions)) {
		for (const [serviceVersion, definition] of Object.entries(versions)) {
			const addressedRoots = new Set<string>()
			for (const kind of ['agent', 'workflow'] as const) {
				for (const [targetName, stored] of Object.entries(
					(kind === 'agent' ? definition.agents : definition.workflows) ?? {},
				)) {
					const rootKind = kind === 'agent' ? 'agents' : 'workflows'
					if (definition.harness && !definition.harness.roots[rootKind].includes(targetName))
						throw new TypeError('Harness client target is not an explicit exported root.')
					if (addressedRoots.has(targetName)) throw new TypeError('Harness root addresses collide across target kinds.')
					addressedRoots.add(targetName)
					const address = { serviceName, serviceVersion, serviceTarget: targetName }
					assertSerializedHarnessTargetExport(address, stored)
					if (stored.kind !== kind)
						throw new TypeError('Harness generated namespace does not match the stored root kind.')
					// This snapshot alone feeds both artifacts; no producer schema or digest is derived here.
					const targetJson = canonicalHarnessJson(stored)
					const target = JSON.parse(targetJson) as typeof stored
					const path = `generated/purista/${safeSegment(convertToKebabCase(serviceName))}/v${safeSegment(serviceVersion)}/harness/${kind}/${safeSegment(convertToKebabCase(targetName))}TargetContract.ts`
					if (files.has(path)) throw new TypeError('Harness generated target paths collide after name normalization.')
					const exportName = `${identifier(convertToCamelCase(targetName))}TargetContract`
					const typeName = identifier(convertToPascalCase(targetName))
					const typeDefinitions = [
						generateSchemaType(`${typeName}Input`, target.inputSchema),
						generateSchemaType(`${typeName}ValidatedInput`, target.validatedInputSchema),
						generateSchemaType(`${typeName}Output`, target.outputSchema),
					].join('\n')
					files.set(
						path,
						`// Generated by ClientBuilder; do not edit.\nimport { createGeneratedHarnessSchema, createRemoteHarnessTargetContract, type JsonValue, type SerializedHarnessTargetExportV1 } from '@purista/core'\n\n${typeDefinitions}\n\nconst serializedTarget = ${targetJson.replace(/"__proto__":/g, '["__proto__"]:')} as const satisfies SerializedHarnessTargetExportV1\nconst targetAddress = ${canonicalHarnessJson(address)} as const\n\nexport const ${exportName} = createRemoteHarnessTargetContract({\n schemaVersion: 1, address: targetAddress, target: serializedTarget,\n schemas: {\n  input: createGeneratedHarnessSchema<${typeName}Input>(serializedTarget.inputSchema),\n  validatedInput: createGeneratedHarnessSchema<${typeName}ValidatedInput>(serializedTarget.validatedInputSchema),\n  output: createGeneratedHarnessSchema<${typeName}Output>(serializedTarget.outputSchema),\n },\n})\n`,
					)
					const imported = `harnessTarget${imports.length}`
					imports.push(`import { ${exportName} as ${imported} } from './${path.replace(/\.ts$/, '.js')}'`)
					let services = namespaces[kind].get(serviceName)
					if (!services) {
						services = new Map()
						namespaces[kind].set(serviceName, services)
					}
					let targets = services.get(serviceVersion)
					if (!targets) {
						targets = []
						services.set(serviceVersion, targets)
					}
					targets.push(
						`[${JSON.stringify(targetName)}]: createRemoteHarnessClient(${imported}, this.__eventBridge__, this.__queueBridge__, { ...this.__harnessClientOptions__, senderName: ${JSON.stringify(clientName)} })`,
					)
				}
			}
		}
	}
	const members = (['agent', 'workflow'] as const)
		.map(kind => {
			const services = [...namespaces[kind]].map(
				([name, versions]) =>
					`[${JSON.stringify(name)}]: { ${[...versions].map(([version, targets]) => `[${JSON.stringify(version)}]: { ${targets.join(',')} }`).join(',')} }`,
			)
			return `get ${kind}() { return { ${services.join(',')} } }`
		})
		.join('\n')
	return { files, imports: imports.join('\n'), members }
}

function safeSegment(value: string): string {
	if (!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(value) || value === '.' || value === '..')
		throw new TypeError('Invalid Harness generated path segment.')
	return value
}

function identifier(value: string): string {
	if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) throw new TypeError('Invalid Harness generated TypeScript identifier.')
	return value
}

function generateSchemaType(name: string, root: HarnessTargetJsonSchema): string {
	const references = new Map<string, string>()
	const aliases: string[] = []
	const render = (schema: HarnessTargetJsonSchema): string => {
		if (schema === false) return 'never'
		if (schema === true) return 'JsonValue'
		if (typeof schema.$ref === 'string') {
			const ref = schema.$ref
			if (ref !== '#' && !ref.startsWith('#/'))
				throw new TypeError('Generated Harness schemas require self-contained local JSON Schema references.')
			const existing = references.get(ref)
			if (existing) return existing
			const referenceName = `${name}Reference${references.size}`
			references.set(ref, referenceName)
			let resolved: unknown = root
			for (const part of (ref === '#' ? [] : ref.slice(2).split('/')).map(value =>
				decodeURIComponent(value).replace(/~1/g, '/').replace(/~0/g, '~'),
			)) {
				if (typeof resolved !== 'object' || resolved === null || !Object.hasOwn(resolved, part))
					throw new TypeError('Unresolved generated Harness schema reference.')
				resolved = (resolved as Record<string, unknown>)[part]
			}
			aliases.push(`type ${referenceName} = ${render(resolved as HarnessTargetJsonSchema)}`)
			return referenceName
		}
		if (Object.hasOwn(schema, 'const')) return JSON.stringify(schema.const)
		if (Array.isArray(schema.enum)) return schema.enum.map(value => JSON.stringify(value)).join(' | ') || 'never'
		const compositions = ['oneOf', 'anyOf', 'allOf'] as const
		for (const key of compositions) {
			if (Array.isArray(schema[key]))
				return (
					(schema[key] as HarnessTargetJsonSchema[])
						.map(value => `(${render(value)})`)
						.join(key === 'allOf' ? ' & ' : ' | ') || 'never'
				)
		}
		if (Array.isArray(schema.type)) return schema.type.map(type => `(${render({ ...schema, type })})`).join(' | ')
		switch (schema.type) {
			case 'string':
				return 'string'
			case 'number':
			case 'integer':
				return 'number'
			case 'boolean':
				return 'boolean'
			case 'null':
				return 'null'
			case 'array': {
				if (Array.isArray(schema.prefixItems)) {
					const prefixItems = schema.prefixItems as HarnessTargetJsonSchema[]
					const min = integerArrayBound(schema.minItems) ?? 0
					const max = integerArrayBound(schema.maxItems)
					if (max !== undefined && min > max) return 'never'
					const additional = schema.items === false ? undefined : ((schema.items ?? true) as HarnessTargetJsonSchema)
					if (additional === undefined && min > prefixItems.length) return 'never'
					const expandedLength = max ?? Math.max(prefixItems.length, min)
					const tupleLength = additional === undefined ? Math.min(prefixItems.length, expandedLength) : expandedLength
					const tuple = Array.from({ length: tupleLength }, (_, index) => {
						const item = render(prefixItems[index] ?? (additional as HarnessTargetJsonSchema))
						return index >= min ? `(${item})?` : item
					})
					if (max === undefined && additional !== undefined) tuple.push(`...(${render(additional)})[]`)
					return `[${tuple.join(', ')}]`
				}
				return `(${render((schema.items ?? true) as HarnessTargetJsonSchema)})[]`
			}
			case 'object': {
				const properties = (schema.properties ?? {}) as Record<string, HarnessTargetJsonSchema>
				const required = new Set(Array.isArray(schema.required) ? schema.required : [])
				const renderedProperties = Object.entries(properties).map(([key, value]) => ({
					key,
					type: render(value),
				}))
				const entries = renderedProperties.map(
					entry => `${JSON.stringify(entry.key)}${required.has(entry.key) ? '' : '?'}: ${entry.type}`,
				)
				const object = entries.length ? `{ ${entries.join('; ')} }` : 'Record<string, never>'
				if (schema.additionalProperties === false) return object
				const additionalType = render((schema.additionalProperties ?? true) as HarnessTargetJsonSchema)
				const indexTypes = [...new Set([additionalType, ...renderedProperties.map(entry => entry.type)])]
				const extra = `Record<string, ${indexTypes.join(' | ')}>`
				return entries.length ? `${object} & ${extra}` : extra
			}
			default:
				return 'JsonValue'
		}
	}
	const result = render(root)
	return [...aliases, `export type ${name} = ${result}`].join('\n')
}

function integerArrayBound(value: unknown): number | undefined {
	return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 ? value : undefined
}

/** @internal Publish one complete generated source tree, rolling back on filesystem failure. */
export async function publishHarnessClientArtifacts(outputPath: string, files: ReadonlyMap<string, string>) {
	await mkdir(outputPath, { recursive: true })
	const transaction = await mkdtemp(join(outputPath, '.harness-client-'))
	const staged = join(transaction, 'src')
	const current = join(outputPath, 'src')
	const backup = join(transaction, 'previous')
	let hadPrevious = false
	let preserveBackup = false
	try {
		try {
			await cp(current, staged, { recursive: true })
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
			await mkdir(staged, { recursive: true })
		}
		await rm(join(staged, 'generated/purista'), { recursive: true, force: true })
		for (const [path, text] of files) {
			const file = join(staged, path)
			await mkdir(dirname(file), { recursive: true })
			await writeFile(file, text)
		}
		try {
			await rename(current, backup)
			hadPrevious = true
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
		}
		try {
			await rename(staged, current)
		} catch (error) {
			if (hadPrevious) {
				try {
					await rename(backup, current)
				} catch (restoreError) {
					preserveBackup = true
					throw new AggregateError(
						[error, restoreError],
						`Unable to restore generated client; previous sources remain at ${backup}.`,
					)
				}
			}
			throw error
		}
	} finally {
		if (!preserveBackup) await rm(transaction, { recursive: true, force: true })
	}
}
