services:
  lowkey-vault:
    container_name: lowkey-vault-nodejs
    image: nagyesta/lowkey-vault:2.4.42
    ports:
      - "8443:8443"
    environment:
      LOWKEY_ARGS: "--server.port=8443"
  assumed-identity:
    container_name: assumed-identity-nodejs
    image: nagyesta/assumed-identity:1.2.16
    ports:
      - "8081:8081"
    environment:
      ASSUMED_ID_PORT: "8081"