name: Pull request

on:
  pull_request:
    branches: ['main']

jobs:
  # Build job
  builddev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      # - uses: pnpm/action-setup@v2 # Uncomment this if you're using pnpm
      # - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm # or pnpm / yarn
      - name: Install dependencies
        run: |
          # rm package-lock.json # https://github.com/npm/cli/issues/4828
          npm ci
      - name: Release readiness checks
        run: npm run release:check
